// AACIO Sales Report — second YouCanBook.me account (external team).
// Same engine as api/ycbm.js but hits the /api/aacio proxy so the two
// accounts never share a cache or auth header. Bookings here ARE the sales
// source for the external (AACIO) team — each coaching-session booking is a
// lead/sale generated by them.

import { cleanCoachName } from './ycbm'

const BASE = '/api/aacio'

async function get(path) {
  const res = await fetch(`${BASE}${path}`, { headers: { Accept: 'application/json' } })
  if (!res.ok) throw new Error(`AACIO API ${res.status}: ${res.statusText}`)
  return res.json()
}

// Window: 45 days back → 14 forward. AACIO is actually HIGH volume (~220
// bookings/week, on par with POTB) — the old 90/60 window needed ~270 pages
// (10 records/page) and the pagination time/page cap ran out BEFORE reaching
// recent dates, so the latest week (what MJ actually views) was undercounted.
// A tighter window paginates fully to today; older history comes from the
// uploaded YCBM report (exact) via mergeWithReport.
// YCBM omits `noShow` and `teamMember` from the default payload — request them
// explicitly. teamMember (the assigned coach) needs the parent AND sub-fields
// listed together or it comes back empty (see api/ycbm.js note).
const BOOKING_FIELDS = 'id,title,startsAt,endsAt,createdAt,cancelled,noShow,profileId,timeZone,location,accountId,tentative,teamMember,teamMember.name,teamMember.email'

const DEFAULT_FROM_DAYS_BACK     = 45
const DEFAULT_TO_DAYS_FORWARD    = 14
const MAX_PAGES                  = 300
const PAGINATION_HARD_TIME_LIMIT = 60000

function toISO(date) {
  return date.toISOString().replace(/\.\d{3}Z$/, 'Z')
}

let _cache = null // { seen: Map, endedAt, window: { start, end } }

export async function fetchAacioBookings({
  fromDaysBack  = DEFAULT_FROM_DAYS_BACK,
  toDaysForward = DEFAULT_TO_DAYS_FORWARD,
} = {}) {
  const now           = new Date()
  const startOfWindow = new Date(now.getTime() - fromDaysBack  * 86400000)
  const endOfWindow   = new Date(now.getTime() + toDaysForward * 86400000)

  let seen = new Map()
  let cursorMs = startOfWindow.getTime()

  if (_cache && _cache.window.start === startOfWindow.getTime()
             && _cache.window.end   === endOfWindow.getTime()) {
    seen = new Map(_cache.seen)
    cursorMs = Math.max(startOfWindow.getTime(), _cache.endedAt - 2 * 86400000)
  }

  let cursor = toISO(new Date(cursorMs))
  const startTime = Date.now()
  let pages = 0
  let latestSeenMs = cursorMs

  while (pages < MAX_PAGES && (Date.now() - startTime) < PAGINATION_HARD_TIME_LIMIT) {
    const page = await get(`/bookings?from=${encodeURIComponent(cursor)}&fields=${BOOKING_FIELDS}`)
    if (!Array.isArray(page) || page.length === 0) break

    let progressed = false
    for (const b of page) {
      seen.set(b.id, b)
      const t = new Date(b.startsAt).getTime()
      if (t > latestSeenMs) { latestSeenMs = t; progressed = true }
    }

    if (!progressed) break
    if (latestSeenMs > endOfWindow.getTime()) break

    cursor = toISO(new Date(latestSeenMs + 1000))
    pages++
  }

  _cache = {
    seen: new Map(seen),
    endedAt: latestSeenMs,
    window: { start: startOfWindow.getTime(), end: endOfWindow.getTime() },
  }

  return [...seen.values()].filter(b => {
    const t = new Date(b.startsAt).getTime()
    return t >= startOfWindow.getTime() && t <= endOfWindow.getTime()
  })
}

export const fetchAacioProfiles = () => get('/profiles')
export const fetchAacioAccount  = () => get('')

// "FirstName and AppointmentType" → { name, appointmentType }
export function parseTitle(title) {
  if (!title) return { name: 'Unknown', appointmentType: '' }
  const i = title.indexOf(' and ')
  if (i === -1) return { name: title, appointmentType: '' }
  return { name: title.slice(0, i).trim(), appointmentType: title.slice(i + 5).trim() }
}

// Local y-m-d key (PHT-safe — never use UTC ISO, it breaks at midnight Manila)
export function dateKey(d) {
  const dt = (d instanceof Date) ? d : new Date(d)
  return `${dt.getFullYear()}-${String(dt.getMonth() + 1).padStart(2, '0')}-${String(dt.getDate()).padStart(2, '0')}`
}

// Map raw AACIO booking → display model
export function mapAacioBooking(raw, profilesById) {
  const { name } = parseTitle(raw.title)
  const profile  = profilesById?.[raw.profileId]
  const start    = new Date(raw.startsAt)
  return {
    id: raw.id,
    name,
    startsAt: raw.startsAt,
    endsAt: raw.endsAt,
    createdAt: raw.createdAt,
    cancelled: !!raw.cancelled,
    // Tri-state attendance. Coaches mark every concluded session in YCBM
    // (finish → noShow:false = SHOWED · no-show → noShow:true), so both bools
    // are REAL marks — verified empirically (a past week returns 0 nulls). Only
    // an ABSENT field (future/not-yet-concluded) maps to null → handled as
    // upcoming downstream. Keeping false (not collapsing it to null) preserves
    // the explicit "showed" signal.
    noShow: raw.noShow === true ? true : raw.noShow === false ? false : null,
    profileId: raw.profileId,
    team: profile?.subdomain ?? 'aacio',
    appointmentType: profile?.title ?? 'Coaching Session',
    coach: cleanCoachName(raw.teamMember?.name),   // assigned coach (Team), or null
    coachEmail: raw.teamMember?.email ?? null,
    timeZone: raw.timeZone,
    hour: start.getHours(),
    raw,
  }
}
